import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const translations = {
  EN: {
    // ============ NAVBAR ============
    home: "Home",
    searchRecords: "Search Records",
    aboutUs: "About Us",
    contactUs: "Contact Us",
    predictValue: "Predict Value",
    dashboard: "Dashboard",
    loginRegister: "Login / Register",
    myDashboard: "My Dashboard",
    language: "Language:",

    // ============ LANDING PAGE ============
    heroTitle1: "Digital Land Records & AI Value",
    heroTitle2: "Prediction for Maharashtra",
    heroSubtitle: "Access land records and get instant land valuation powered by Machine Learning",
    searchPlaceholder: "survey_no",
    map: "Map",
    new: "NEW",
    totalRecords: "Total Records",
    villagesCovered: "Villages Covered",
    predictionsMade: "Predictions Made",
    mlAccuracy: "ML Model Accuracy",
    howItWorks: "How It Works",
    howItWorksSubtitle: "Get your land records and AI-powered valuations in 4 simple steps",
    step1Title: "Search Records",
    step1Desc: "Enter survey number, village, or owner name to find land records",
    step2Title: "View Details",
    step2Desc: "Access complete land documentation with verified details",
    step3Title: "AI Prediction",
    step3Desc: "Get instant land value predictions powered by machine learning",
    step4Title: "Download & Save",
    step4Desc: "Store and access your reports anytime from your dashboard",
    importantNotice: "Important Notice",
    noticeText: "🔔 Bhoomi Seva v2.0 Launched • 1,000+ Land Records Digitized • AI Value Prediction with 99.8% Accuracy • 3 Villages of Morshi Covered • Register Now for Instant Access to Land Records",
    bhoomiSevaHindi: "भूमि-सेवा",
    bhoomiSevaEng: "Bhoomi Seva",
    footerTagline: "Digital Land Records and AI Value Prediction",
    quickLinks: "Quick Links",
    contact: "Contact",
    copyright: "© 2026 Copyright. All rights reserved.",
    developedFor: "Developed for Revenue Department | Powered by AI & Machine Learning",
    maharashtraMap: "Maharashtra Divisions Map",
    close: "Close",

    // ============ ABOUT PAGE ============
    aboutBadge: "About Bhoomi Seva",
    aboutHeroTitle: "Revolutionizing Land Records",
    aboutHeroSubtitle: "Digital Land Management System powered by AI & Machine Learning for Government of Maharashtra",
    ourMissionLabel: "Our Mission",
    aboutSectionTitle: "Making Land Records Accessible to Everyone",
    aboutPara1a: "Bhoomi Seva is a comprehensive digital platform designed to modernize land record management in Maharashtra. We leverage cutting-edge technologies including",
    aboutPara1b: "Artificial Intelligence, Machine Learning, and Cloud Computing",
    aboutPara1c: "to provide instant access to land records and AI-powered valuations.",
    aboutPara2: "Our platform serves citizens, revenue officers, and property buyers by providing accurate, verified, and instantly accessible land information from government-verified databases.",
    mlAccuracyLabel: "ML Accuracy",
    whatWeOffer: "What We Offer",
    keyFeatures: "Key Features",
    feature1Title: "Digital Land Records",
    feature1Desc: "Complete digital access to 1,000+ verified land records from Morshi Taluka villages.",
    feature2Title: "AI-Powered Valuation",
    feature2Desc: "Get instant property value predictions using our ML models trained on historical data.",
    feature3Title: "GIS Map Integration",
    feature3Desc: "Visualize land parcels, boundaries, and infrastructure on interactive maps.",
    feature4Title: "Secure & Verified",
    feature4Desc: "All records are verified from government databases with end-to-end encryption.",
    feature5Title: "Instant Access",
    feature5Desc: "Search by survey number, village, or owner name and get results in seconds.",
    feature6Title: "Predictive Analytics",
    feature6Desc: "Understand land value trends and make informed property decisions.",
    poweredBy: "Powered By",
    technologyStack: "Technology Stack",
    techSubtitle: "Built with modern, scalable, and reliable technologies",
    techBackend: "Backend API",
    techFrontend: "Frontend UI",
    techDatabase: "Database",
    techMlApi: "ML API",
    techMlModel: "ML Model",
    techStyling: "Styling",
    techIntegration: "Integration",
    techAiEngine: "AI Engine",
    ourImpact: "Our Impact",
    landRecords: "Land Records",
    ourVision: "Our Vision",
    ourVisionDesc: "To create India's most trusted digital land records platform that empowers citizens with transparent, accessible, and AI-driven property information services.",
    ourMission: "Our Mission",
    ourMissionDesc: "To digitize and simplify land record management for Maharashtra Government, providing instant access, AI-powered valuations, and seamless services to every citizen.",
    readyToStart: "Ready to Get Started?",
    readyToStartDesc: "Access land records and AI-powered valuations today",

    // ============ CONTACT PAGE ============
    contactUsTitle: "Contact Us",
    contactUsSubtitle: "We're here to help you with any queries",
    callUs: "Call Us",
    callUsHours: "Mon-Sat, 9 AM - 6 PM",
    emailUs: "Email Us",
    emailResponse: "Response within 24 hours",
    visitUs: "Visit Us",
    visitUsAddress: "Amravati District, Maharashtra",
    visitUsDept: "Revenue Department, Morshi",
    sendMessage: "Send us a Message",
    thankYouMessage: "✅ Thank you! Your message has been sent successfully.",
    yourName: "Your Name",
    yourEmail: "Your Email",
    subject: "Subject",
    yourMessage: "Your Message",
    sendMessageBtn: "Send Message",

    // ============ SEARCH PAGE ============
    searchPageTitle: "Search Land Records",
    totalRecordsLabel: "Total Records:",
    showingLabel: "Showing:",
    filters: "Filters",
    clearAll: "Clear All",
    searchInputPlaceholder: "Survey No, Village, Owner...",
    allVillages: "All Villages",
    allLandTypes: "All Land Types",
    loadingRecords: "Loading records from database...",
    noRecordsFound: "No records found",
    tryAdjusting: "Try adjusting your filters",
    clearFilters: "Clear Filters",
    tableHash: "#",
    tableSurveyNo: "Survey No",
    tableVillage: "Village",
    tableOwner: "Owner",
    tableLandType: "Land Type",
    tableArea: "Area",
    tableMarketPrice: "Market Price",
    tableRoad: "Road",
    tableActions: "Actions",
    viewDetails: "View Details",
    download: "Download",
    showing: "Showing",
    to: "to",
    of: "of",
    recordsWord: "records",
    landRecord: "Land Record:",
    surveyNumber: "Survey Number",
    villageLabel: "Village",
    ownerName: "Owner Name",
    landTypeLabel: "Land Type",
    landArea: "Land Area",
    marketPrice: "Market Price",
    roadConnectivity: "Road Connectivity",
    distanceHighway: "Distance from Highway",
    distanceCity: "Distance from City",
    downloadReport: "Download Report",

    // ============ LOGIN PAGE (ADD THESE) ============
// EN
logIn: "LOG IN",
emailMobileSevarth: "Email Address, Mobile Number or Sevarth Id",
captcha: "Captcha",
citizen: "Citizen",
admin: "Admin",
enterCaptcha: "Enter captcha",
invalidCaptcha: "Invalid captcha",

// ============ REGISTER PAGE ============
createAccount: "Create Account",
signUp: "SIGN UP",
registerSubtitle: "Register to access land records and services",
fullName: "Full Name",
fullNamePlaceholder: "Enter your full name",
mobileNumber: "Mobile Number",
mobilePlaceholder: "Enter 10-digit mobile number",
confirmPassword: "Confirm Password",
confirmPasswordPlaceholder: "Re-enter your password",
selectRole: "Register As",
agreeTerms: "I agree to the Terms & Conditions",
register: "Register",
registering: "Registering...",
alreadyHaveAccount: "Already have an account?",
loginHere: "Login Here",
passwordMismatch: "Passwords do not match",
mustAgreeTerms: "You must agree to the terms",
  },

  MR: {
    // ============ NAVBAR ============
    home: "मुख्यपृष्ठ",
    searchRecords: "नोंदी शोधा",
    aboutUs: "आमच्याबद्दल",
    contactUs: "संपर्क करा",
    predictValue: "मूल्य अंदाज",
    dashboard: "डॅशबोर्ड",
    loginRegister: "लॉगिन / नोंदणी",
    myDashboard: "माझा डॅशबोर्ड",
    language: "भाषा:",

    // ============ LANDING PAGE ============
    heroTitle1: "डिजिटल भूमी अभिलेख आणि AI मूल्य",
    heroTitle2: "महाराष्ट्रासाठी अंदाज",
    heroSubtitle: "मशीन लर्निंगद्वारे भूमी अभिलेख प्रवेश करा आणि त्वरित भूमी मूल्यांकन मिळवा",
    searchPlaceholder: "सर्व्हे क्रमांक",
    map: "नकाशा",
    new: "नवीन",
    totalRecords: "एकूण नोंदी",
    villagesCovered: "समाविष्ट गावे",
    predictionsMade: "केलेले अंदाज",
    mlAccuracy: "ML मॉडेल अचूकता",
    howItWorks: "हे कसे कार्य करते",
    howItWorksSubtitle: "४ सोप्या चरणांमध्ये आपले भूमी अभिलेख आणि AI-आधारित मूल्यांकन मिळवा",
    step1Title: "नोंदी शोधा",
    step1Desc: "सर्व्हे क्रमांक, गाव, किंवा मालकाचे नाव प्रविष्ट करून भूमी अभिलेख शोधा",
    step2Title: "तपशील पहा",
    step2Desc: "सत्यापित तपशीलांसह संपूर्ण भूमी दस्तऐवज मिळवा",
    step3Title: "AI अंदाज",
    step3Desc: "मशीन लर्निंगद्वारे त्वरित भूमी मूल्य अंदाज मिळवा",
    step4Title: "डाउनलोड आणि जतन करा",
    step4Desc: "आपल्या डॅशबोर्डवरून कधीही अहवाल जतन आणि प्रवेश करा",
    importantNotice: "महत्वाची सूचना",
    noticeText: "🔔 भूमी सेवा v2.0 लाँच • 1,000+ भूमी अभिलेख डिजिटायझेशन • 99.8% अचूकतेसह AI मूल्य अंदाज • मोर्शीची 3 गावे समाविष्ट • भूमी अभिलेखांच्या त्वरित प्रवेशासाठी आत्ता नोंदणी करा",
    bhoomiSevaHindi: "भूमि-सेवा",
    bhoomiSevaEng: "भूमी सेवा",
    footerTagline: "डिजिटल भूमी अभिलेख आणि AI मूल्य अंदाज",
    quickLinks: "जलद दुवे",
    contact: "संपर्क",
    copyright: "© २०२६ कॉपीराइट. सर्व हक्क राखीव.",
    developedFor: "महसूल विभागासाठी विकसित | AI आणि मशीन लर्निंगद्वारे सक्षम",
    maharashtraMap: "महाराष्ट्र विभाग नकाशा",
    close: "बंद करा",

    // ============ ABOUT PAGE ============
    aboutBadge: "भूमी सेवाबद्दल",
    aboutHeroTitle: "भूमी अभिलेखांमध्ये क्रांती",
    aboutHeroSubtitle: "महाराष्ट्र शासनासाठी AI आणि मशीन लर्निंगद्वारे सक्षम डिजिटल भूमी व्यवस्थापन प्रणाली",
    ourMissionLabel: "आमचे ध्येय",
    aboutSectionTitle: "सर्वांसाठी भूमी अभिलेख प्रवेशयोग्य बनवणे",
    aboutPara1a: "भूमी सेवा हे महाराष्ट्रातील भूमी अभिलेख व्यवस्थापन आधुनिक करण्यासाठी डिझाइन केलेले सर्वसमावेशक डिजिटल प्लॅटफॉर्म आहे. आम्ही अत्याधुनिक तंत्रज्ञान वापरतो ज्यामध्ये",
    aboutPara1b: "कृत्रिम बुद्धिमत्ता, मशीन लर्निंग आणि क्लाउड कंप्युटिंग",
    aboutPara1c: "यांचा समावेश आहे, जेणेकरून भूमी अभिलेख आणि AI-आधारित मूल्यांकनांमध्ये त्वरित प्रवेश मिळवता येईल.",
    aboutPara2: "आमचे प्लॅटफॉर्म नागरिक, महसूल अधिकारी आणि मालमत्ता खरेदीदारांना अचूक, सत्यापित आणि त्वरित प्रवेशयोग्य भूमी माहिती सरकारी-सत्यापित डेटाबेसमधून प्रदान करते.",
    mlAccuracyLabel: "ML अचूकता",
    whatWeOffer: "आम्ही काय ऑफर करतो",
    keyFeatures: "मुख्य वैशिष्ट्ये",
    feature1Title: "डिजिटल भूमी अभिलेख",
    feature1Desc: "मोर्शी तालुक्यातील गावांमधील 1,000+ सत्यापित भूमी अभिलेखांना संपूर्ण डिजिटल प्रवेश.",
    feature2Title: "AI-आधारित मूल्यांकन",
    feature2Desc: "ऐतिहासिक डेटावर प्रशिक्षित आमच्या ML मॉडेल्सचा वापर करून त्वरित मालमत्ता मूल्य अंदाज मिळवा.",
    feature3Title: "GIS नकाशा एकीकरण",
    feature3Desc: "परस्परसंवादी नकाशांवर भूमी पार्सल, सीमा आणि पायाभूत सुविधा पहा.",
    feature4Title: "सुरक्षित आणि सत्यापित",
    feature4Desc: "सर्व अभिलेख शेवटपासून शेवटपर्यंत एन्क्रिप्शनसह सरकारी डेटाबेसमधून सत्यापित केले जातात.",
    feature5Title: "त्वरित प्रवेश",
    feature5Desc: "सर्व्हे क्रमांक, गाव किंवा मालकाचे नाव शोधा आणि सेकंदात परिणाम मिळवा.",
    feature6Title: "भविष्यसूचक विश्लेषण",
    feature6Desc: "भूमी मूल्य ट्रेंड समजून घ्या आणि माहितीपूर्ण मालमत्ता निर्णय घ्या.",
    poweredBy: "द्वारे सक्षम",
    technologyStack: "तंत्रज्ञान स्टॅक",
    techSubtitle: "आधुनिक, स्केलेबल आणि विश्वासार्ह तंत्रज्ञानाने बनवलेले",
    techBackend: "बॅकएंड API",
    techFrontend: "फ्रंटएंड UI",
    techDatabase: "डेटाबेस",
    techMlApi: "ML API",
    techMlModel: "ML मॉडेल",
    techStyling: "स्टाइलिंग",
    techIntegration: "एकीकरण",
    techAiEngine: "AI इंजिन",
    ourImpact: "आमचा प्रभाव",
    landRecords: "भूमी अभिलेख",
    ourVision: "आमची दृष्टी",
    ourVisionDesc: "भारतातील सर्वात विश्वासार्ह डिजिटल भूमी अभिलेख प्लॅटफॉर्म तयार करणे जे नागरिकांना पारदर्शक, प्रवेशयोग्य आणि AI-आधारित मालमत्ता माहिती सेवा प्रदान करते.",
    ourMission: "आमचे ध्येय",
    ourMissionDesc: "महाराष्ट्र शासनासाठी भूमी अभिलेख व्यवस्थापन डिजिटायझ आणि सोपे करणे, प्रत्येक नागरिकाला त्वरित प्रवेश, AI-आधारित मूल्यांकन आणि निर्बाध सेवा प्रदान करणे.",
    readyToStart: "सुरुवात करण्यास तयार आहात?",
    readyToStartDesc: "आजच भूमी अभिलेख आणि AI-आधारित मूल्यांकन मिळवा",

    // ============ CONTACT PAGE ============
    contactUsTitle: "संपर्क करा",
    contactUsSubtitle: "आम्ही आपल्या कोणत्याही प्रश्नांमध्ये मदत करण्यास येथे आहोत",
    callUs: "आम्हाला कॉल करा",
    callUsHours: "सोम-शनि, सकाळी ९ - संध्याकाळी ६",
    emailUs: "आम्हाला ईमेल करा",
    emailResponse: "२४ तासांत प्रतिसाद",
    visitUs: "आम्हाला भेट द्या",
    visitUsAddress: "अमरावती जिल्हा, महाराष्ट्र",
    visitUsDept: "महसूल विभाग, मोर्शी",
    sendMessage: "आम्हाला संदेश पाठवा",
    thankYouMessage: "✅ धन्यवाद! आपला संदेश यशस्वीरित्या पाठविला गेला आहे.",
    yourName: "आपले नाव",
    yourEmail: "आपला ईमेल",
    subject: "विषय",
    yourMessage: "आपला संदेश",
    sendMessageBtn: "संदेश पाठवा",

    // ============ SEARCH PAGE ============
    searchPageTitle: "भूमी अभिलेख शोधा",
    totalRecordsLabel: "एकूण नोंदी:",
    showingLabel: "दाखवत आहे:",
    filters: "फिल्टर",
    clearAll: "सर्व साफ करा",
    searchInputPlaceholder: "सर्व्हे क्र., गाव, मालक...",
    allVillages: "सर्व गावे",
    allLandTypes: "सर्व भूमी प्रकार",
    loadingRecords: "डेटाबेसमधून नोंदी लोड करत आहे...",
    noRecordsFound: "कोणतीही नोंद सापडली नाही",
    tryAdjusting: "आपले फिल्टर समायोजित करण्याचा प्रयत्न करा",
    clearFilters: "फिल्टर साफ करा",
    tableHash: "#",
    tableSurveyNo: "सर्व्हे क्र.",
    tableVillage: "गाव",
    tableOwner: "मालक",
    tableLandType: "भूमी प्रकार",
    tableArea: "क्षेत्रफळ",
    tableMarketPrice: "बाजार भाव",
    tableRoad: "रस्ता",
    tableActions: "क्रिया",
    viewDetails: "तपशील पहा",
    download: "डाउनलोड",
    showing: "दाखवत आहे",
    to: "ते",
    of: "पैकी",
    recordsWord: "नोंदी",
    landRecord: "भूमी अभिलेख:",
    surveyNumber: "सर्व्हे क्रमांक",
    villageLabel: "गाव",
    ownerName: "मालकाचे नाव",
    landTypeLabel: "भूमी प्रकार",
    landArea: "भूमी क्षेत्रफळ",
    marketPrice: "बाजार भाव",
    roadConnectivity: "रस्ता कनेक्टिव्हिटी",
    distanceHighway: "हायवेपासून अंतर",
    distanceCity: "शहरापासून अंतर",
    downloadReport: "अहवाल डाउनलोड करा",

    logIn: "लॉग इन",
emailMobileSevarth: "ईमेल पत्ता, मोबाइल क्रमांक किंवा सेवार्थ आयडी",
captcha: "कॅप्चा",
citizen: "नागरिक",
admin: "प्रशासक",
enterCaptcha: "कॅप्चा प्रविष्ट करा",
invalidCaptcha: "अवैध कॅप्चा",

createAccount: "खाते तयार करा",
signUp: "साइन अप",
registerSubtitle: "भूमी अभिलेख आणि सेवांमध्ये प्रवेश करण्यासाठी नोंदणी करा",
fullName: "पूर्ण नाव",
fullNamePlaceholder: "आपले पूर्ण नाव प्रविष्ट करा",
mobileNumber: "मोबाइल क्रमांक",
mobilePlaceholder: "१० अंकी मोबाइल क्रमांक प्रविष्ट करा",
confirmPassword: "पासवर्ड पुष्टी करा",
confirmPasswordPlaceholder: "आपला पासवर्ड पुन्हा प्रविष्ट करा",
selectRole: "म्हणून नोंदणी करा",
agreeTerms: "मी अटी व शर्ती मान्य करतो",
register: "नोंदणी करा",
registering: "नोंदणी करत आहे...",
alreadyHaveAccount: "आधीच खाते आहे?",
loginHere: "येथे लॉगिन करा",
passwordMismatch: "पासवर्ड जुळत नाहीत",
mustAgreeTerms: "आपण अटींशी सहमत असणे आवश्यक आहे",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem("language") || "EN";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang) => setLanguageState(lang);
  const toggleLanguage = () => setLanguageState((prev) => (prev === "EN" ? "MR" : "EN"));
  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);